package py.com.cbi.pykasu.web.ws.debitos;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390-
 * Generated source version: 2.0
 * <p>
 * An example of how this class may be used:
 * 
 * <pre>
 * ws_tri_liq service = new ws_tri_liq();
 * WsTriLiqSoapPort portType = service.getWsTriLiqSoapPort();
 * portType.execute(...);
 * </pre>
 * 
 * </p>
 * 
 */
@WebServiceClient(name = "ws_tri_liq", targetNamespace = "services", wsdlLocation = "http://localhost:9000/vision-wsdl-pagos/services/ws_tri_liqSoapPort")
public class WsTriLiq extends Service {

	private final static URL WSTRILIQ_WSDL_LOCATION;
	private final static Logger logger = Logger
			.getLogger(py.com.cbi.pykasu.web.ws.debitos.WsTriLiq.class
					.getName());

	static {
		URL url = null;
		try {
			URL baseUrl;
			baseUrl = py.com.cbi.pykasu.web.ws.debitos.WsTriLiq.class
					.getResource(".");
			url = new URL(
					baseUrl,
					"http://localhost:9000/vision-wsdl-pagos/services/ws_tri_liqSoapPort");
		} catch (MalformedURLException e) {
			logger.warning("Failed to create URL for the wsdl Location: 'http://localhost:9000/tributos_web/servlet/srv.aws_tri_liq', retrying as a local file");
			logger.warning(e.getMessage());
		}
		WSTRILIQ_WSDL_LOCATION = url;
	}

	public WsTriLiq(URL wsdlLocation, QName serviceName) {
		super(wsdlLocation, serviceName);
	}

	public WsTriLiq() {
		super(WSTRILIQ_WSDL_LOCATION, new QName("services", "ws_tri_liq"));
	}

	/**
	 * 
	 * @return returns WsTriLiqSoapPort
	 */
	@WebEndpoint(name = "ws_tri_liqSoapPort")
	public WsTriLiqSoapPort getWsTriLiqSoapPort() {
		return super.getPort(new QName("services", "ws_tri_liqSoapPort"),
				WsTriLiqSoapPort.class);
	}

}
