package py.com.cbi.pykasu.web.ws.debitos;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390-
 * Generated source version: 2.0
 * 
 */
@WebService(name = "ws_tri_liqSoapPort", targetNamespace = "services")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface WsTriLiqSoapPort {

	/**
	 * 
	 * @param parameters
	 * @return returns py.com.cbi.pykasu.web.ws.debitos.WsTriLiqExecuteResponse
	 */
	@WebMethod(operationName = "Execute", action = "servicesaction/AWS_TRI_LIQ.Execute")
	@WebResult(name = "ws_tri_liq.ExecuteResponse", targetNamespace = "services", partName = "parameters")
	public WsTriLiqExecuteResponse execute(
			@WebParam(name = "ws_tri_liq.Execute", targetNamespace = "services", partName = "parameters") WsTriLiqExecute parameters);

}
