package py.com.cbi.pykasu.web.ws.cuentas;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390-
 * Generated source version: 2.0
 * 
 */
@WebService(name = "ws_tri_salSoapPort", targetNamespace = "services")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface WsTriSalSoapPort {

	/**
	 * 
	 * @param parameters
	 * @return returns py.com.cbi.pykasu.web.ws.WsTriSalExecuteResponse
	 */
	@WebMethod(operationName = "Execute", action = "servicesaction/AWS_TRI_SAL.Execute")
	@WebResult(name = "ws_tri_sal.ExecuteResponse", targetNamespace = "services", partName = "parameters")
	public WsTriSalExecuteResponse execute(
			@WebParam(name = "ws_tri_sal.Execute", targetNamespace = "services", partName = "parameters") WsTriSalExecute parameters);

}
